In [1]:
from scripts.AbstractExperiments import ExperimentRunner
from scripts.TexTables import SaveDataFrameToTexTemplate
from copy import deepcopy
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt

In [ ]:
defaultConfig = {"Budget": 3, "Horizon": 6}
inputConfigs = {
    "(Hal)": {"Theories": [["Hal", "Utility", 0]], "Considerations": [["Hal", "Hal"]]},
}
if True:
    newConfigs = {}
    for i in range(3, 8):
        for key, value in inputConfigs.items():
            newConfigs[f"H={str(i).rjust(3,'0')}_{key}"] = deepcopy(value)
            newConfigs[f"H={str(i).rjust(3,'0')}_{key}"]["Horizon"] = i

inputConfigs = newConfigs

Config_repetitions=1
Environment_repetitions = 10
configs = []
for name, dat in inputConfigs.items():
    c = deepcopy(defaultConfig)
    c["Name"] = name
    c["Theories"] = dat["Theories"]
    c["Considerations"] = dat["Considerations"]
    c["Budget"] = dat["Budget"] if "Budget" in dat.keys() else c["Budget"]
    c["Horizon"] = dat["Horizon"] if "Horizon" in dat.keys() else c["Horizon"]
    configs.append(c)

In [20]:
er = ExperimentRunner("LostInsulin", configs, MoralPlanner_Location="/../")
er.buildEnvironments(configRepetitions=1)
er.run(configRepetitions=Config_repetitions, envRepetitions=Environment_repetitions)

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Hal)^0_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^0, (Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^0, (Necessity)^0, (Hal)^0_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Hal)^0_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^0, (Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^0, (Necessity)^0, (Hal)^0_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Hal)^0_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Law)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Law)^0, (Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Law)^0, (Necessity)^0, (Hal)^0_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 689 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=006_(Hal)^0_con0.json

Written LostInsulin MMMDP with 689 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=006_(Law)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 689 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=006_(Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 689 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=006_(Law)^0, (Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 689 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=006_(Law)^0, (Necessity)^0, (Hal)^0_con0.json

Written LostInsulin MMMDP with 689 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=006_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 689 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=006_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 877 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=007_(Hal)^0_con0.json

Written LostInsulin MMMDP with 877 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=007_(Law)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 877 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=007_(Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 877 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=007_(Law)^0, (Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 877 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=007_(Law)^0, (Necessity)^0, (Hal)^0_con0.json

Written LostInsulin MMMDP with 877 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=007_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 877 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=007_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Hal)^0_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^0, (Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^0, (Necessity)^0, (Hal)^0_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 167 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=003_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Hal)^0_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^0, (Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^0, (Necessity)^0, (Hal)^0_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 321 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 1}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=004_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Hal)^0_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Law)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 1}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Law)^0, (Necessity)^0, (Hal)^1_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Law)^0, (Necessity)^0, (Hal)^0_con0.json

Written LostInsulin MMMDP with 501 states and theories [{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}, {'Name': 'Necessity', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'OrdinalLaw', 'Type': 'Ordinal', 'Rank': 0}, {'Name': 'Carla', 'Type': 'Utility', 'Rank': 0}].
PATH  /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/mdps/H=005_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0_con0.json


In [23]:
er.saveResults()
df = pd.DataFrame(er.data)
df = df[df["Config_name"]=="H=006_(Hal)^0"]
df.head(1000)

                                         Config_name  Heuristic_time  \
0                                      H=003_(Hal)^0            61.3
1                             H=003_(Law)^0, (Hal)^1           145.7
2                       H=003_(Necessity)^0, (Hal)^1            86.0
3              H=003_(Law)^0, (Necessity)^0, (Hal)^1           136.4
4              H=003_(Law)^0, (Necessity)^0, (Hal)^0           126.3
5   H=003_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0           211.0
6   H=003_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0           161.6
7                                      H=004_(Hal)^0            98.8
8                             H=004_(Law)^0, (Hal)^1           186.7
9                       H=004_(Necessity)^0, (Hal)^1           217.7
10             H=004_(Law)^0, (Necessity)^0, (Hal)^1           276.3
11             H=004_(Law)^0, (Necessity)^0, (Hal)^0           269.3
12  H=004_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0           395.7
13  H=004_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0           350.3
14                                     H=005_(Hal)^0           183.5
15                            H=005_(Law)^0, (Hal)^1           392.7
16                      H=005_(Necessity)^0, (Hal)^1           415.6
17             H=005_(Law)^0, (Necessity)^0, (Hal)^1           792.2
18             H=005_(Law)^0, (Necessity)^0, (Hal)^0           937.4
19  H=005_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0          1049.0
20  H=005_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0           796.0
21                                     H=006_(Hal)^0           270.2
22                            H=006_(Law)^0, (Hal)^1           716.8
23                      H=006_(Necessity)^0, (Hal)^1           659.9
24             H=006_(Law)^0, (Necessity)^0, (Hal)^1           925.7
25             H=006_(Law)^0, (Necessity)^0, (Hal)^0           829.9
26  H=006_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0          1112.9
27  H=006_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0          1077.9
28                                     H=007_(Hal)^0           326.7
29                            H=007_(Law)^0, (Hal)^1           661.9
30                      H=007_(Necessity)^0, (Hal)^1           836.8
31             H=007_(Law)^0, (Necessity)^0, (Hal)^1          1497.2
32             H=007_(Law)^0, (Necessity)^0, (Hal)^0          1174.5
33  H=007_(Law)^0, (Necessity)^0, (Hal)^0, (Carla)^0          1726.2
34  H=007_(Law)^1, (Necessity)^1, (Hal)^0, (Carla)^0          1544.9

    Plan_time  Sol_time  Mehr_time  Total_time  Backups  Num_of_sols
0        82.8      73.8        1.3       219.2     28.0          1.0
1       396.6     287.2        2.8       832.3     98.0          3.0
2       150.1     178.0        1.9       416.0     54.0          2.0
3       292.1     276.8        3.7       709.0     98.0          3.0
4       276.1     269.4        3.7       675.5     98.0          3.0
5       390.5     354.0        9.6       965.1    121.0          5.0
6       376.0     347.6        6.1       891.3    121.0          5.0
7       103.5      91.0        1.1       294.4     47.0          1.0
8       750.0     748.5        2.3      1687.5    296.0          3.0
9       298.1     329.6        1.9       847.3    122.0          2.0
10      867.2     859.6        3.0      2006.1    296.0          3.0
11      834.2     832.1        3.5      1939.1    296.0          3.0
12     1111.2    1588.2       12.5      3107.6    315.0          6.0
13     1108.5    1599.1        8.9      3066.8    315.0          6.0
14      188.4     161.9        1.0       534.8     93.0          1.0
15     2645.9    2820.0        5.5      5864.1    831.0          4.0
16     1315.8    1316.1        2.9      3050.4    519.0          3.0
17     3153.1    3719.5        6.9      7671.7    831.0          5.0
18     3652.5    4061.1       10.1      8661.1    831.0          5.0
19     4279.2    7166.8       37.8     12532.8    670.0         10.0
20     3216.9    5699.2       19.9      9732.0    670.0         10.0
21      241.3     209.1        1.0       721.6    135.0          1.0
22     4274.5    4036.8        4.1      9032.2   1520.0          4.0
23     2201.8    2072.6        3.0      4937.3    790.0          3.0
24     4842.9    4708.7        6.3     10483.6   1520.0          5.0
25     4809.0    4775.8        8.8     10423.5   1520.0          5.0
26     5892.8   11517.4       68.9     18592.0   1089.0         18.0
27     5710.6   11113.2       38.8     17940.5   1089.0         18.0
28      334.6     276.4        1.2       938.9    199.0          1.0
29     4300.7    5030.5        3.5      9996.6   1413.0          4.0
30     1041.2    1263.7        3.3      3145.0    357.0          3.0
31     6255.1    8075.8        7.4     15835.5   1425.0          5.0
32     5451.4    6742.1        8.9     13376.9   1425.0          5.0
33    11046.9   28987.6      246.0     42006.7   1083.0         35.0
34     9906.9   26906.8      132.8     38491.4   1083.0         35.0
Successfully saved populated LaTeX to /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/tex/time_table.tex
Successfully saved populated LaTeX to /Users/user/Desktop/MyMoralPlanner/MoralPlanner/Notebooks/../Data/Experiments/LostInsulin/2026-06-18_15:41:27/tex/Utility_table.tex

,Config_name,Conf_rep,Env_rep,Theories,Considerations,Total_time,Heuristic_time,Plan_time,Mehr_time,CQ1_time,...,Horizon,Min_non_accept,Num_of_min_non_accept,Num_of_sols,Total_Attacks,Total_reachable_policies,Hal,Legality,Necessity,Carla
210,H=006_(Hal)^0,0,0,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",693,254,234,1,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A
211,H=006_(Hal)^0,0,1,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",676,235,235,1,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A
212,H=006_(Hal)^0,0,2,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",707,243,248,1,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A
213,H=006_(Hal)^0,0,3,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",716,265,241,1,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A
214,H=006_(Hal)^0,0,4,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",697,249,241,1,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A
215,H=006_(Hal)^0,0,5,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",740,263,254,1,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A
216,H=006_(Hal)^0,0,6,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",679,237,233,1,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A
217,H=006_(Hal)^0,0,7,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",675,238,234,1,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A
218,H=006_(Hal)^0,0,8,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",671,236,234,0,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A
219,H=006_(Hal)^0,0,9,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",962,482,259,2,0,...,7,0.0,1,1,0,507068,-55.2698,N/A,N/A,N/A

In [15]:

df.head(100)

,Config_name,Conf_rep,Env_rep,Theories,Considerations,Total_time,Heuristic_time,Plan_time,Mehr_time,CQ1_time,...,Total_states,Backups,Iterations,Horizon,Min_non_accept,Num_of_min_non_accept,Num_of_sols,Total_Attacks,Total_reachable_policies,Hal
0,H=003_(Hal),0,0,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",220,61,87,2,0,...,167,28,5,4,0.0,1,1,0,811,-60.6997
1,H=003_(Hal),0,1,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",185,48,70,1,0,...,167,28,5,4,0.0,1,1,0,811,-60.6997
2,H=003_(Hal),0,2,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",187,50,70,1,0,...,167,28,5,4,0.0,1,1,0,811,-60.6997
3,H=003_(Hal),0,3,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",202,54,78,2,0,...,167,28,5,4,0.0,1,1,0,811,-60.6997
4,H=003_(Hal),0,4,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",181,48,68,1,0,...,167,28,5,4,0.0,1,1,0,811,-60.6997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,H=007_(Hal)_7,0,5,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",1053,350,391,1,0,...,877,199,9,8,0.0,1,1,0,6262515,-53.5391
96,H=007_(Hal)_7,0,6,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",962,324,352,1,0,...,877,199,9,8,0.0,1,1,0,6262515,-53.5391
97,H=007_(Hal)_7,0,7,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",959,330,346,1,0,...,877,199,9,8,0.0,1,1,0,6262515,-53.5391
98,H=007_(Hal)_7,0,8,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",941,328,336,1,0,...,877,199,9,8,0.0,1,1,0,6262515,-53.5391
99,H=007_(Hal)_7,0,9,"[{'Name': 'Hal', 'Type': 'Utility', 'Rank': 0}]","[{'Type': 'Hal', 'Component_of': 'Hal'}]",990,356,349,1,0,...,877,199,9,8,0.0,1,1,0,6262515,-53.5391